MODULE_NAME='MODULE_IR_V1' (DEV IRPort, DEV MVP[], INTEGER BUTTONS[], INTEGER OFFSET, INTEGER PULSE_TIME)

DEFINE_VARIABLE



DEFINE_EVENT


BUTTON_EVENT [MVP,BUTTONS]    
{
PUSH:   {
         SET_PULSE_TIME (PULSE_TIME) PULSE [IRPort,button.input.channel - OFFSET]
        }
HOLD[3]:{
       TO [IRPort,button.input.channel - OFFSET]
	}
}


